### PR TITLE
feat: add `throwIfAborted`, `timeout` & `any` methods

### LINKED ISSUE #70: Support throwIfAborted()
There is a modern API method to throw abort reason, if operation was aborted: `AbortSignal.throwIfAborted()`.

**WhatWG specification:** https://dom.spec.whatwg.org/#ref-for-dom-abortsignal-throwifaborted

**Example implementation:** nodejs/node#40951

If would be great if this polyfill will support it.

### LINKED ISSUE #73: Support AbortSignal.timeout
See https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout

> The static AbortSignal.timeout() method returns an [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) that will automatically abort after a specified time.

### PR DESCRIPTION
**Pull request by TechQuery**
1. fix #70
2. fix #73

### CODE REVIEW

**Comment by mo** [comment]
Thank you for submitting these improvements.. I have merged your fixes and I did a few more adjustments as well to make sure it matched browser behavior and passed all tests etc... a new version 1.7.6 has been published

**Comment by TechQuery** [comment]
> Thank you for submitting these improvements.. I have merged your fixes and I did a few more adjustments as well to make sure it matched browser behavior and passed all tests etc... a new version 1.7.6 has been published

But I see no new Git commit in `master` branch.

**Comment by mo** [comment]
should be pushed now

**Comment by TechQuery** [comment]
> should be pushed now

And those issues haven't been closed.

**Pull request closed without merging**
