### PR TITLE
#26 Fix detection of broken AbortController on new versions of Safari and Technology Preview.

### PR DESCRIPTION
**Pull request by macku**
Starting from version 12.2 the Safari browser will ship the implemented version of the abordable fetch API.

I decided to use the [`Bowser`](https://github.com/lancedikson/bowser) NPM package to parse the user agent of a browser.

### CODE REVIEW

**Comment by caub** [comment]
feature detection is probably better than user-agent detection

@homer0 Could I ask you what you meant by ["The native AbortController is just a stub that doesn't actually abort."](https://github.com/mo/abortcontroller-polyfill/commit/256fde6b551678bbb72a7821c1fdbb734bfbe84a)? Because I'm almost sure this polyfill doesn't actually abort the request too, it just throw an Error, and reject a wrapped fetch, but it wouldn't affect the fetch request

**Comment by mo** [comment]
@caub Really old versions of Safari didn't have window.AbortController at all. Certain versions including the current stable version of Safari has a window.AbortController defined, but this AbortController is such that if you call .abort() on it before even making the fetch request, the fetch will still happen and the promise will resolve rather than reject with an AbortError. However, the latest technical preview has fixed this and it looks like they will ship a working AbortController in the next stable version. Beyond Safari, this issue also affects Chrome for IOS and Firefox for IOS etc since they use the same platform-supplied version of webkit. More details here: https://bugs.webkit.org/show_bug.cgi?id=174980#c2

**Comment by mo** [comment]
@macku pulling in bowser takes the umd bundle quite a bit larger... I don't have time to look into this in-depth right now (hopefully I can have a look this weekend or so) but I wonder what the overhead would be for minimal ua sniff specific to this issue

**Comment by mo** [comment]
Because this PR increased the umd bundle size a bit too much, I tried out an alternative solution today where I changed the "is native AbortController is broken" condition to explicitly list Safari 12.0.x and 12.1.x as well as Chrome/Firefox for IOS. This isn't as maintainable/clean as this PR but I decided to go with that solution anyway to keep the bundle size small and the dependency list short. Hopefully v1.2.3 from master should work well in place of this PR. Thanks a lot for reporting the issue and working on this PR though.

**Comment by macku** [comment]
I agree, my solution was a bit overcomplicated and I didn't check the bundle size. Thanks for looking into this!

**Pull request closed without merging**
