### PR TITLE
feat: add polyfill that only supports AbortSignal

### LINKED ISSUE #78: Enhance AbortSignal
Hello. When running in the Android WebView environment, the native AbortController and AbortSignal are available. However, the instances of AbortSignal only support the aborted property. I just want to extend the AbortSignal alone to support the reason property, the throwIfAborted method and static methods, instead of completely replacing AbortSignal. Is this approach supported?

### PR DESCRIPTION
**Pull request by l246804**
fix #78

### CODE REVIEW

**Comment by l246804** [comment]
@mo Hello, Please review. Thanks!

**Comment by mo** [comment]
if you have a partial implementation of AbortController and you want to use the polyfill anyway, it's possible to set this global before importing:
window.__FORCE_INSTALL_ABORTCONTROLLER_POLYFILL = true;

Can you solve your usecase by simply forcing installing the polyfill instead?

Note 1) "npm test" does not pass on the branch.

Note 2) that all the polyfill code was originally tested in MSIE 11 which has some atrocious quirks like for example you cannot invoke the DOMException constructor via: "new DOMException('Aborted', 'AbortError')". Right now I don't even have a virtual machine with IE11 available so maybe it's probably a good time to release an abortcontroller-polyfill 2.x version with IE11 support removed. However, it will still be necessary to test a lot of older browsers other than MSIE 11 before releasing it. Unfortunately, I'm really busy with other stuff right now so I don't have time to work on such testing/release. Hopefully, you can force install the polyfill and solve your issue that way.

**Comment by l246804** [comment]
> if you have a partial implementation of AbortController and you want to use the polyfill anyway, it's possible to set this global before importing: window.__FORCE_INSTALL_ABORTCONTROLLER_POLYFILL = true;
> 
> Can you solve your usecase by simply forcing installing the polyfill instead?
> 
> Note 1) "npm test" does not pass on the branch.
> 
> Note 2) that all the polyfill code was originally tested in MSIE 11 which has some atrocious quirks like for example you cannot invoke the DOMException constructor via: "new DOMException('Aborted', 'AbortError')". Right now I don't even have a virtual machine with IE11 available so maybe it's probably a good time to release an abortcontroller-polyfill 2.x version with IE11 support removed. However, it will still be necessary to test a lot of older browsers other than MSIE 11 before releasing it. Unfortunately, I'm really busy with other stuff right now so I don't have time to work on such testing/release. Hopefully, you can force install the polyfill and solve your issue that way.

I have added the global variable flag.

This polyfill is mainly applied in the environment of old Android WebViews. On mobile phones from 2017 to 2022, the compatibility of AbortSignal.reason is not ideal. And there are still many users using mobile phones during this period.

The reason why the full polyfill is not directly used is that although the native fetch exists, it does not support non-native AbortSignal. Otherwise, an exception will be thrown.

image

**Comment by mo** [comment]
merged to master now and released as 1.7.7

**Pull request merged**
