### PR TITLE
Broken native abortcontroller polyfill on Safari 11.x

### PR DESCRIPTION
**Pull request by SairamSrinivasan**
I ran into a problem using this polyfill with the current version of Safari. Safari 11.x has the abortcontroller defined, but it does not actually abort the request... Seeing this, the regular expression only detects 12 and 12.1. I shortened the regular expression to use an or case, and added Safari 11 to the list of conditions.

### CODE REVIEW

**Comment by mo** [comment]
Thanks for the PR!

In which 11.x version was it where you saw the "available but broken" AbortController?

**Comment by SairamSrinivasan** [comment]
I am running 11.1.2

**Comment by SairamSrinivasan** [comment]
@mo Has there been an update to this review?

**Comment by mo** [comment]
@SairamSrinivasan not yet, I hope I will find some time to test it this weekend

**Comment by SairamSrinivasan** [comment]
Understood. Thanks for giving me an update.

**Comment by mo** [comment]
Thanks for the patch! Merged to master and released on npm as v1.2.4

**Comment by pilar1347** [comment]
I think this may be causing an issue in Chrome iPhone emulator (with has a user agent of Safari 11.0). With version 1.2.4 I am seeing this error: 
screen shot 2019-02-19 at 8 34 04 am

**Comment by mo** [comment]
@pilar1347 can you visit http://pages.minimum.se/ua/ with the broken browser and post the full user agent string here on this issue?

Also, which version of iOS was running the emulator?

**Comment by pilar1347** [comment]
Full user agent string is: userAgent=Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1vendor=Google Inc.

I believe the iOS is v11 - The Chrome v is 72.0.3626.109

**Comment by mo** [comment]
@pilar1347 does http://pages.minimum.se/abortcontroller-polyfill-testapp/ eventually render with green or red background color on this device?

**Comment by pilar1347** [comment]
It does not render - white page with same error as above.

**Comment by SairamSrinivasan** [comment]
It's bizarre that you're able to hit this check. Can you please use the Safari emulator and share your experiences?

**Comment by SairamSrinivasan** [comment]
The reason why I say that it's bizarre is that the abortcontroller-polyfill checks if self.abortController exists before checking if a broken version of AbortController exists natively. Through research I've found out that the abort controller was introduced in Safari 11.1.2. If you're running 11, a version that the AbortController didn't exist, the RegEx match should not even run, for the reason of the && operator and the first check failing.

**Comment by pilar1347** [comment]
Interesting - today I'm seeing different results running the link http://pages.minimum.se/abortcontroller-polyfill-testapp/ in Chrome emulator iPhone X I get the following result: 
screen shot 2019-02-20 at 9 38 47 am
On Safari emulator green screens all the way, not seeing an issue.

**Comment by mo** [comment]
At first I misunderstood what "Chrome iPhone emulator" referred to, but I eventually realized that you meant running the latest version of Chrome on desktop, and then activating the "device mode" in devtools and switching to "iPhone mode" there. This means we're still running Chrome, with a working abortcontroller, but the user agent is changed so that the Chrome-browser presents itself as Safari running on an iPhone. This explains why the abortcontroller polyfill saw window.AbortController even though the user agent string said "Safari 11.0". This means that this bug probably only manifests itself in debugging environments like this devtools setup and not on actual iPhones. Indeed, I have tested the polyfill under a very wide range of iOS devices via testingbot.com and it looks good there. Nevertheless I think this is still a bug worth fixing.

I experimented a bit with a potential fix earlier which is why the testapp doesn't display the same behavior right now (it's running a pre-release version of the polyfill). Unfortunately, I have not yet found a fix that covers all of the use cases at once. I hope to find some time to have another look at this though.

**Comment by mo** [comment]
@pilar1347 The bug you found should be fixed on master now (and released as v1.2.5)

**Pull request closed without merging**
